<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="ImageDisplay.fs" />
        <Compile Include="ComputeShaders.fs" />
        <Compile Include="Raycast.Compute.fs" />
        <Content Include="env.js" />
        <Content Include="worker.js" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Dootverse.WebGPU.fsproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Bolero.WebView" Version="2024.7.26.27" />
      <PackageReference Include="FSharp.Data.LiteralProviders" Version="1.0.3" />
      <PackageReference Include="GirCore.Gtk-4.0" Version="0.5.0" />
      <PackageReference Include="WatsonWebsocket" Version="4.1.2" />
      
    </ItemGroup>

</Project>
