<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RootNamespace>PGA</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        
        <Content Include="Library.Code.fs"/>
        <Compile Include="PGA2D.fs" />
        <Compile Include="Library.fs"/>
        <Compile Include="Voxel.Traversal.fs" />
        <PackageReference Include="Fable.Core" Version="4.0.0" />
        <PackageReference Include="Fable.Fetch" Version="2.6.0" />
    </ItemGroup>

<!--    <ItemGroup>-->
<!--      <ProjectReference Include="..\Algebra\Algebra.csproj" />-->
<!--    </ItemGroup>-->

</Project>
