<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Global.fs" />
    <Compile Include="Settings.fs" />
    <Compile Include="Init.fs" />
<!--    <Compile Include="RaymarchingVertexFragmentShader.fs" />-->
<!--    <Compile Include="DdaVertexFragmentShader.fs" />-->
<!--    <Compile Include="SimpleVoxelRender.fs" />-->
<!--    <Compile Include="DdaRaymarchRender.fs" />-->
    <Compile Include="HashmapVoxelRender.fs" />
    <Compile Include="RendererStart.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dootverse.WebGPU.fsproj" />
<!--    <ProjectReference Include="..\Raycast.Compute\Raycast.Compute.fsproj" />-->
  </ItemGroup>
</Project>